### ISSUE TITLE
OpenMP is still enabled in setup.py even though it's not used in code

### ISSUE THREAD

**Issue by Kirill888** [daleroberts/hdstats#16]
This block needs to go, openmp is no longer in the code

https://github.com/daleroberts/hdstats/blob/bd5fe85a0a299797f2f6bd6a476ef07e9ddeeb16/setup.py#L19-L25

**Comment by Kirill888** [comment]
used in MADs coputation.

**Comment by RichardScottOZ** [comment]
Yes, the multiprocessing looks like the thing I need to work out to use this
